import React from 'react';
import styles from './Typography.module.css';

/**
 * VWDS Typography
 *
 * Every variant maps 1:1 to a semantic typography token
 * (see tokens/vwds.tokens.json -> semantic.typography).
 * No literal font values live here — the CSS Module reads
 * --vwds-semantic-typography-* variables generated by Style Dictionary.
 */

export type TypographyVariant =
  | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  | 'subtitle1' | 'subtitle2'
  | 'body1' | 'body2'
  | 'overline' | 'caption'
  | 'editorial-body';

export type TypographyColor =
  | 'primary' | 'secondary' | 'tertiary' | 'link' | 'on-action' | 'inherit';

// Which HTML element each variant renders by default (semantics != style).
const defaultElement: Record<TypographyVariant, string> = {
  h1: 'h1', h2: 'h2', h3: 'h3', h4: 'h4', h5: 'h5', h6: 'h6',
  subtitle1: 'p', subtitle2: 'p',
  body1: 'p', body2: 'p',
  overline: 'span', caption: 'span',
  'editorial-body': 'p',
};

export interface TypographyProps
  extends React.HTMLAttributes<HTMLElement> {
  /** Visual style — maps to a semantic typography token. */
  variant?: TypographyVariant;
  /** Text color role — maps to a semantic color token. */
  color?: TypographyColor;
  /**
   * Override the rendered HTML tag without changing the visual style.
   * e.g. a section title that looks like h2 but must be an h1 for document outline.
   */
  as?: keyof JSX.IntrinsicElements;
  children: React.ReactNode;
}

export const Typography = ({
  variant = 'body1',
  color = 'primary',
  as,
  className,
  children,
  ...rest
}: TypographyProps) => {
  const Element = (as ?? defaultElement[variant]) as React.ElementType;

  const classes = [
    styles.root,
    styles[`variant-${variant}`],
    styles[`color-${color}`],
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <Element className={classes} {...rest}>
      {children}
    </Element>
  );
};

Typography.displayName = 'Typography';
